# Generated by Django 3.2.13 on 2022-06-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0002_rename_blog_todoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='datecomplited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
